import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import type { CreateQuotationDTO, QuotationItemForm } from "./quotation.types";

interface DownloadQuotationPDFProps {
  quotationNumber: string;
  quotationType: "LEAD" | "CUSTOMER";
  targetName?: string;
  projectName?: string;
  payload: CreateQuotationDTO;
  items: QuotationItemForm[];
  subtotal: number;
  discountAmount: number;
  totalAmount: number;
}

export function downloadQuotationPDF({
  quotationNumber,
  quotationType,
  targetName,
  projectName,
  payload,
  items,
  subtotal,
  discountAmount,
  totalAmount,
}: DownloadQuotationPDFProps) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // -----------------------------
  // Header
  // -----------------------------
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("QUOTATION", 14, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  doc.text(`Quotation No : ${quotationNumber}`, 14, 28);
  doc.text(`Created On : ${new Date().toLocaleDateString()}`, 140, 28);

  doc.line(14, 33, 196, 33);

  // -----------------------------
  // Details
  // -----------------------------
  doc.setFontSize(11);

  doc.text(
    `${quotationType === "LEAD" ? "Lead" : "Customer"} : ${targetName ?? "-"}`,
    14,
    42,
  );

  doc.text(`Project : ${projectName ?? "-"}`, 14, 50);

  doc.text(`Phase : ${payload.phase}`, 14, 58);

  doc.text(`Valid Until : ${payload.validUntil ?? "-"}`, 14, 66);

  // -----------------------------
  // Items
  // -----------------------------
  const rows = items
    .filter((item) => item.productId)
    .map((item) => [
      item.productName ?? item.search,
      item.quantity.toString(),
      `${item.marginPercent}%`,
      `₹ ${item.sellingPrice.toFixed(2)}`,
      `₹ ${item.totalPrice.toFixed(2)}`,
    ]);

  autoTable(doc, {
    startY: 75,

    head: [["Product", "Qty", "Margin %", "Rate", "Amount"]],

    body: rows,

    styles: {
      fontSize: 10,
      cellPadding: 3,
    },

    headStyles: {
      fillColor: [33, 37, 41],
      textColor: 255,
      fontStyle: "bold",
    },

    columnStyles: {
      1: {
        halign: "center",
      },
      2: {
        halign: "center",
      },
      3: {
        halign: "right",
      },
      4: {
        halign: "right",
      },
    },
  });

  const finalY =
    (
      doc as jsPDF & {
        lastAutoTable?: {
          finalY: number;
        };
      }
    ).lastAutoTable?.finalY ?? 75;

  // -----------------------------
  // Totals
  // -----------------------------
  doc.setFontSize(11);

  doc.text(`Subtotal : ₹ ${subtotal.toFixed(2)}`, 140, finalY + 12);

  doc.text(`Discount : ₹ ${discountAmount.toFixed(2)}`, 140, finalY + 20);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);

  doc.text(`Total : ₹ ${totalAmount.toFixed(2)}`, 140, finalY + 32);

  // -----------------------------
  // Notes
  // -----------------------------
  if (payload.notes) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);

    doc.text("Notes", 14, finalY + 48);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    const lines = doc.splitTextToSize(payload.notes, 180);

    doc.text(lines, 14, finalY + 56);
  }

  // -----------------------------
  // Footer
  // -----------------------------
  doc.setDrawColor(200);

  doc.line(14, 285, 196, 285);

  doc.setFontSize(9);

  doc.text("Generated by NKP CRM", 14, 291);

  const pdfBlob = doc.output("blob");
  const pdfUrl = URL.createObjectURL(pdfBlob);

  window.open(pdfUrl, "_blank");
}
